// Generated by Wrangler by running `wrangler types ./worker/worker-configuration.d.ts`

interface Env {
	ASSETS: Fetcher;
	MIDDLECACHE: R2Bucket;
	// Service binding to the standalone devdocs-ai-search-indexer worker.
	AI_SEARCH_WORKER: Fetcher;
}
declare module "*/__redirects" {
	const value: string;
	export default value;
}
